/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/rakscard.glb -o tmp.jsx 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/rakscard.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[0.835, -0.031, 0.437]} rotation={[-0.009, 0.002, 0.002]}>
        <mesh geometry={nodes.Mesh_0001.geometry} material={materials['base.001']} />
        <mesh geometry={nodes.Mesh_0001_1.geometry} material={materials['Material.002']} />
        <mesh geometry={nodes.Mesh_0001_2.geometry} material={materials['Material.003']} />
      </group>
      <mesh geometry={nodes.clamp001.geometry} material={materials['metal.001']} position={[0.835, -0.031, 0.437]} />
      <mesh geometry={nodes.clip001.geometry} material={materials['metal.001']} position={[0.835, -0.031, 0.437]} />
    </group>
  )
}

useGLTF.preload('/rakscard.glb')
